### ISSUE TITLE
Moderators don't show up / Subsetting issues

### ISSUE THREAD

**Issue by christinabergmann** [langcog/metalab2#92]
1. I don't see moderators that are specified in the yaml on the visualization page. 
2. Subsets are generated using binary columns, but there seems to be an issue for the rule learning dataset. 

Maybe someone has an idea why these issues occur.

**Comment by juliacarbajal** [comment]
This should solve the problem, we'll see tomorrow when the website reloads if it did the trick!

**Comment by christinabergmann** [comment]
Subsetting still doesn't work for prosocial and for nonspeech in rule learning, so I am reopening.
In all cases the spreadsheet use TRUE / FALSE so I don't see what could be happening.

**Comment by juliacarbajal** [comment]
Fixed. I forgot to mention what the problem was before: adding the variables in datasets.yaml is not enough for them to be used as moderators or subsetting, they need to also be added to spec.yaml or otherwise it won't be able to find them (you can check that any variables missing from spec.yaml will also not appear in the data tables in the website). So these two steps are necessary.

I had corrected many of the moderators and subsetting variables that were missing before, but I had forgotten to add Hamlin_Leb to spec.yaml (that's because when I was first solving this problem, the Prosocial MA was not appearing in the website), and Nonspeech was miss-spelled (I accidentally wrote Nonpeech).

Now it should all work next time the website is refreshed. If you find any other variables missing just let me know and I'll add them to spec.yaml.

**Comment by christinabergmann** [comment]
Ah fantastic, but it shows that we need some heavy documentation for how to add datasets, even for us nerds, because it's such a rare event that I forget. 😞

**Comment by alecristia** [comment]
Just reopening this to remind myself that Angeline pointed out that her moderators are not showing up. I see from Julia's response that I should check spec.yaml

**Comment by alecristia** [comment]
I added the three, but:

- in the metalab version of the dataset, the three relevant columns are missing (I also notice it says "under review"): http://metalab.stanford.edu/dataset/switchTask.html#Data
- in the linked dataset, they are not: https://docs.google.com/spreadsheets/d/1qkGFqZLwuuO5ELKiFg4E5EGX5O6xTfJC_hxyZXJr2zI/edit

But let's wait and see if this fixes the issue.

**Comment by christinabergmann** [comment]
The MetaLab data have been processed through spec.yaml so columns get dropped for all datasets. Your fix should work, once the site is re-rendered. Thanks for working this out!
